#!/bin/bash
# just capturing all the options for gcc_build in a script
# so I don't have to retype them again 

../gcc-4.8.1/configure                                \
    --target=$LFS_TGT                                 \
    --prefix=/tools                                   \
    --with-sysroot=$LFS                               \
    --with-newlib                                     \
    --without-headers                                 \
    --with-local-prefix=/tools                        \
    --with-native-system-header-dir=/tools/include    \
    --disable-nls                                     \
    --disable-shared                                  \
    --disable-multilib                                \
    --disable-decimal-float                           \
    --disable-threads                                 \
    --disable-libatomic                               \
    --disable-libgomp                                 \
    --disable-libitm                                  \
    --disable-libmudflap                              \
    --disable-libquadmath                             \
    --disable-libsanitizer                            \
    --disable-libssp                                  \
    --disable-libstdc++-v3                            \
    --enable-languages=c,c++                          \
    --with-mpfr-include=$(pwd)/../gcc-4.8.1/mpfr/src  \
    --with-mpfr-lib=$(pwd)/mpfr/src/.libs
make
make install
ln -sv libgcc.a `$LFS_TGT-gcc -print-libgcc-file-name | sed 's/libgcc/&_eh/'`

